"""add coupons model

Revision ID: 0892524bb487
Revises: 5af99b9bd93b
Create Date: 2022-10-28 00:02:41.735343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0892524bb487'
down_revision = '5af99b9bd93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('procentage', sa.Float(precision=2), nullable=True),
    sa.Column('started_ad', sa.DateTime(), nullable=True),
    sa.Column('ended_ad', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    # ### end Alembic commands ###
