"""add model ubdate

Revision ID: 123afbbfec80
Revises: 10eb4c83e90c
Create Date: 2022-10-27 16:56:28.837615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123afbbfec80'
down_revision = '10eb4c83e90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('wallet', sa.Column('wallet_account_id', sa.Integer(), nullable=True))
    op.drop_constraint('wallet_wallet_id_fkey', 'wallet', type_='foreignkey')
    op.create_foreign_key(None, 'wallet', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'wallet', 'wallet_account', ['wallet_account_id'], ['id'])
    op.drop_column('wallet', 'wallet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_foreign_key('wallet_wallet_id_fkey', 'wallet', 'wallet_account', ['wallet_id'], ['id'])
    op.drop_column('wallet', 'wallet_account_id')
    op.drop_column('wallet', 'user_id')
    # ### end Alembic commands ###
