"""add model shoppingCart and relationship games, game_articles

Revision ID: 3883fabe2a50
Revises: c51dc44d58c6
Create Date: 2022-10-27 14:30:38.403937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3883fabe2a50'
down_revision = 'c51dc44d58c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('games_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['game_articles.id'], ),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart')
    # ### end Alembic commands ###
