"""add model categories

Revision ID: 58436032c855
Revises: c6c92392dc0e
Create Date: 2022-10-27 11:38:24.340575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58436032c855'
down_revision = 'c6c92392dc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
