"""wallet_model update

Revision ID: 5af99b9bd93b
Revises: 123afbbfec80
Create Date: 2022-10-27 22:39:43.062522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af99b9bd93b'
down_revision = '123afbbfec80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'status')
    # ### end Alembic commands ###
