"""Agrega campo stado a |roles|

Revision ID: a928e9470802
Revises: f0725893200d
Create Date: 2022-09-05 17:22:35.671082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a928e9470802'
down_revision = 'f0725893200d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'status')
    # ### end Alembic commands ###
