"""upgrade game_articles

Revision ID: af2012ff520e
Revises: 0892524bb487
Create Date: 2022-10-28 12:07:54.102641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2012ff520e'
down_revision = '0892524bb487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_account', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_account', 'status')
    # ### end Alembic commands ###
