"""Agrega clave foranea entre users & roles

Revision ID: f0725893200d
Revises: 6582c2750bec
Create Date: 2022-09-05 17:13:06.871588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0725893200d'
down_revision = '6582c2750bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
